### ISSUE TITLE
Cache dependencies in CI runner

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#108]
The CI runner takes an increasing amount of time to resolve package dependencies. This has resulted in build times running up to 10min for the Python 3.10 build. We should cache the dependencies for a while on the CI runner, so as to avoid these very long runtimes.

EDIT: I'm pretty sure scipy/statsmodels solved this in some way, so their CI scipts would be a good place to start.

**Comment by N-Wouda** [comment]
It's mostly poetry that cannot resolve the dependencies very quickly. That seems to be a common issue: https://github.com/python-poetry/poetry/issues/2094.

**Comment by N-Wouda** [comment]
Relevant pre-commit stuff: https://tobiasmcnulty.com/posts/caching-pre-commit/

**Comment by markkvdb** [comment]
The setup-python action for GitHub Actions supports caching poetry dependencies out of the box. Minimal example to make things run:

```
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.2.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install
      - name: Lint
        run: poetry run bash scripts/lint.sh
```

I don't know why but `pipx` is installed by default for the GitHub runners.
